### PR TITLE
Create Device Swap

### PR DESCRIPTION
**Pull request by wwAMRA**
Part of Camara drop 2 APIs. The API name is Device Swap

### CODE REVIEW

**Comment by jordonezlucena** [comment]
The API proposal complies with the template

**Review by hdamker — COMMENTED** [review]
@wwAMRA 
* File name should have .md extension to make it readable
* Please check with @ToshiWakayama-KDDI if he wants to be listed as initial API contributor

**Comment by ShutingQing** [comment]
We have interest in Device Swap, and proposed similar idea in https://github.com/camaraproject/SimSwap/issues/36 . After discussion with Waseem, we will support and contribute in this API.

**Review by jordonezlucena — APPROVED** [review]
LGTM

**Pull request merged**
