### PR TITLE
Update APIbacklog.md

### PR DESCRIPTION
**Pull request by ShutingQing**
Update Network Slice Booking.

### CODE REVIEW

**Comment by DanXu-ChinaTelecom** [comment]
Agree with the update

**Review by DanXu-ChinaTelecom — APPROVED** [review]

**Comment by hdamker** [comment]
@ShutingQing @DanXu-ChinaTelecom @TEF-RicardoSerr The proposal was and is still listed as "Network Slicing". We haven't changed the first column in other cases as well.

@TEF-RicardoSerr when moving to an own repository we need also to setup code owners to avoid such short-cut merges.

**Comment by ShutingQing** [comment]
> @ShutingQing @DanXu-ChinaTelecom @TEF-RicardoSerr The proposal was and is still listed as "Network Slicing". We haven't changed the first column in other cases as well.
> 
> @TEF-RicardoSerr when moving to an own repository for API Backlog we need also to setup code owners to avoid such short-cut merges.

Hi Herbert. So the name of proposal and repository are supposedly different right? I think I misunderstand the Proposal name here. Since last TSC suggested to rename the repo from "Network Slicing API" to "Network Slice Booking API". So that's the reason why I updated it. Should I modify it back to Network Slicing?

**Comment by ShutingQing** [comment]
Updated in https://github.com/camaraproject/WorkingGroups/pull/390 . Please reviewers take a look.

**Comment by hdamker** [comment]
> Hi Herbert. So the name of proposal and repository are supposedly different right? I think I misunderstand the Proposal name here. Since last TSC suggested to rename the repo from "Network Slicing API" to "Network Slice Booking API". So that's the reason why I updated it. Should I modify it back to Network Slicing?

Yes, the proposal is still the same one (https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/SupportingDocuments/API%20proposals/APIproposal_NetworkSlicing_ChinaUnicom.md), the resulting repository is also in the table. I'm not saying that this is the best way to handle it, but we have done it this way in other cases.

**Pull request merged**
