### PR TITLE
new API proposal- Site to cloud VPN

### PR DESCRIPTION
**Pull request by DanXu-ChinaTelecom**
Hello colleagues,

This pr is for issue #271.
Please review proposal template and solution introdution(PPT) of site to cloud VPN API.

### CODE REVIEW

**Comment by DanXu-ChinaTelecom** [comment]
Based on API Backlog regular meeting discussion, we need to share the IETF document (RFC) specifying the network API on top of which S2C VPN API will be built, so the information provided is as follows:
RFC9291: L2 VPN Network Model
RFC9182: L3 VPN Network Model
RFC 6241: Network Configuration Protocol (NETCONF) and etc.

**Comment by DanXu-ChinaTelecom** [comment]
If you are interested in this API, please contact me to become a supporter, thank you in advance.

**Comment by DanXu-ChinaTelecom** [comment]
This API aims to provide multi-site, multi-cloud network connection for customers, and provide virtual private network services for industries and applications such as  education, medical, Internet of things, cloud desktop, cloud conference, cloud recording and etc.

Two actual business use cases are as follows: The first is a digital exhibition application that needs to render a digital model in the central cloud and use the rendering model in the edge cloud.The digital exhibition application deployed in local site  subscribes the cloud resources and the S2C VPN API service between local site and edge cloud,  thus the customers to the digital  exhibition hall in the local site can access rendering application with large bandwidth and will enjoy good experience.
The second use case is for cloud court which requires secure and large bandwidth to deliver trial video materials to the central cloud since these video materials need to be stored for a long time(maybe 20 years), so cloud court application is suitable to call  S2C VPN API to achieve elastic, private and secure data delivery and storage.

**Comment by hdamker** [comment]
@DanXu-ChinaTelecom The PR unfortunately replaces the complete table in APIBacklog.md, so it is not possible to see what is changed and if not previous merged lines will be overwritten. I propose that you exclude the table from this PR, but instead doing a seperate PR to add/change the one line within the APIBacklog (as it doesn't need a discussion). Please don't forget to work on the latest content of main branch.

**Comment by DanXu-ChinaTelecom** [comment]
redo

**Comment by hdamker** [comment]
The redone PR replaces still the complete table in APIBacklog.md and is not based on the current version of the table in branch `main`.

**Review by jordonezlucena — APPROVED** [review]
API proposal complies with the template

**Pull request merged**
