### PR TITLE
Create new API proposal-Verified Caller

### PR DESCRIPTION
**Pull request by DanXu-ChinaTelecom**
This API allows accurate operator-certified "Verified Caller" information, including SMS and video clips, to be displayed on the phone screen of the called user before they answer the call. 
This API enables enterprise customers to vividly present their multimedia business cards and reduces the incidence of malicious calls. It is applicable to customers in industries such as government, finance, express delivery, healthcare, education, etc., who have outbound call requirements.

### CODE REVIEW

**Comment by DanXu-ChinaTelecom** [comment]
This is from GSMA drop4 priority list (the first item).

**Comment by Jason-ZTE** [comment]
Due to the prevalence of online fraud and cybercrime as significant challenges in e-commerce, GSMA, mobile operators, and technical partners are prioritizing the GSMA Open Gateway initiative to address online crime.。This API, authenticated by operators, delivers consumer business cards, significantly reducing the likelihood of fraud calls while ensuring legitimate calls are easily received by consumers. We believe many operators have initiated similar ventures. Let's collaborate to advance the global standardization of this business and API.

**Review by chinaunicomyangfan — APPROVED** [review]

**Review by TEF-RicardoSerr — CHANGES_REQUESTED** [review]
This PR can not be merged until approval in the API Backlog

**Review by TEF-RicardoSerr — APPROVED** [review]

**Comment by TEF-RicardoSerr** [comment]
Merging as for the last meeting decissions (minutes available [here](https://wiki.camaraproject.org/display/CAM/2024-05-09+API+backlog+minutes)

**Pull request merged**
