### PR TITLE
Update APIbacklog.md

### PR DESCRIPTION
**Pull request by jordonezlucena**
Clean-up for backlog table

### CODE REVIEW

**Comment by hdamker** [comment]
Changed my role from assignee to reviewer. Editor of this PR is @jordonezlucena

**Review by MarkusKuemmerle — COMMENTED** [review]
Please also update ProjectStructureAndRoles.md that the process description fits to the changes made in the table

**Comment by hdamker** [comment]
> Please also update ProjectStructureAndRoles.md that the process description fits to the changes made in the table

@MarkusKuemmerle Good point. Just that the process and table is described in https://github.com/camaraproject/Governance/blob/main/documentation/API-onboarding.md (ProjectStructureAndRoles.md contains just a link to this file).

@jordonezlucena I propose to do that in a separate PR.

**Comment by bigludo7** [comment]
Hello - Thanks for that.
I've still a small comments:
- we have one line for Device location which covers several APIs: device location verification & geofencing + one line for device location retrieval
- while we have 3 lines for KYC which are in the same family.

Should we have a distinct column for API Family name and API name ?

**Comment by hdamker** [comment]
@jordonezlucena We urgently need to have progress here ... the APIBacklog.md within main is outdated (none of the new proposals which are today in TSC are in).

**Comment by jordonezlucena** [comment]
let's agree this baseline table first and proceed with PR merge. The rest of issues/questions, let's treat them afterwards via separate PRs. 
@bigludo7: as Herbert has pointed out, we urgently need to merge this PR, since the version available in main branch is quite outdate in content and format. If you agree with the table, please approve it and I answer your questions separately afterwards.

**Review by bigludo7 — APPROVED** [review]
Approved as requested by  @jordonezlucena 
There is still for me an inconsistency between API & API Family but we can discuss this later.

**Pull request merged**
