### PR TITLE
Update CAMARA-AuthN-AuthZ-Concept.md

### PR DESCRIPTION
**Pull request by jordonezlucena**
- Adding user identity clause

### CODE REVIEW

**Comment by jpengar** [comment]
> Adding user identity clause

some furhter details about the change:

- Proposed to remove sentence "The Camara Service APIs in most use cases will make use of the client crendentials grant.". We do believe that this could be potencially not 100% true according to legal teams (every time some personal data is processed even when it is provided like an API input e.g. IP address it would require the user consent legally speaking). So it's more than enough what is perfectly explained in doc by:

```
Client Credentials grant: (when user resource is not involved & the client belongs to confidential category)
Authorization Code grant: (when user resource is involved)
```

- User consent Management proposal is treated as a separated document (https://github.com/camaraproject/WorkingGroups/pull/68) but we have added OIDC CIBA flow and jwt-bearer as part of the Relevant authorization grants and flows. It is part of the User Consent Management proposal as well.

- Added clarification about user identity in authentication and the concept of "end user" in the context of CAMRA APIs being exposed by Telco operators. Being different from UE identification included in PR https://github.com/camaraproject/WorkingGroups/pull/51

**Comment by shilpa-padgaonkar** [comment]
@jpengar : Agree on removing sentence about client_credentials would be used mostly.
Will review the other additions.

**Comment by jordonezlucena** [comment]
This has been moved to PR #80

**Comment by shilpa-padgaonkar** [comment]
duplicate of pr #80

**Pull request closed without merging**
