### PR TITLE
Proposal for KYC Age Verification API

### PR DESCRIPTION
**Pull request by bigludo7**
Proposal for KYC Age Verification API

### CODE REVIEW

**Comment by bigludo7** [comment]
@eric-murray @jordonezlucena Sorry for the question but I'm not yet familiar with the process.
Do I have to update the [APIBacklog.md](https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/APIBacklog.md) file ? or is it at your hand when you prepare the meeting?
Thanks.

**Comment by jordonezlucena** [comment]
> @eric-murray @jordonezlucena Sorry for the question but I'm not yet familiar with the process.
> Do I have to update the [APIBacklog.md](https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/APIBacklog.md) file ? or is it at your hand when you prepare the meeting?
> Thanks.

No, the API owner should only proceed with the submission of the filled-in template, as reported [here](https://github.com/camaraproject/Governance/blob/main/documentation/API-onboarding.md#submission-of-an-api-proposal). The backlog group chair will be responsible for updating the  [APIBacklog.md](https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/APIBacklog.md) accordingly. Another reason not to update the backlog right now is because there is #331 ongoing.

**Comment by bigludo7** [comment]
Thanks @jordonezlucena

**Comment by jordonezlucena** [comment]
As reported in the [minutes](https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/MeetingMinutes/MOM-2023-11-02.md) of last conf. call, this API will be taken for TSC approval.

**Review by jordonezlucena — APPROVED** [review]

**Pull request merged**
