### PR TITLE
Fixing bugs detected on a new review

### PR DESCRIPTION
**Pull request by RubenBG7**
- Propose of the document "CAMARA APIs"
- Pattern deleted from statud field due to change from string to int
- stranger red format color fixed

### CODE REVIEW

**Review by hdamker — CHANGES_REQUESTED** [review]
Several comments:
* #149 is still open, these fixes should go there
* The diff shows a complete replacement ... that can't be easily reviewed
* I would consider this file as a collection of **examples** for (potential) common data and error formats as part of the API design guidelines. That should be also stated within the API design guidelines. Not all of the definitions I could already accept as binding. The renaming could be misunderstood as already binding.
* The error model seems to be too complex (see discussion in https://github.com/camaraproject/QualityOnDemand/pull/104).
* Some of the definitions are specific to few APIs only or not even used at all (e.g. MoneyAmount) ... common definitions should be only introduced if really needed (and already used/tested in the APIs)

Regarding the future use of common component definitions:
* Before we can use and import such common component definitions within Camara APIs we would need to solve a bunch of topics, e.g. versioning and change process for common definitions and handling of dependencies between repositories. 
* In particular the WorkingGroups repo shouldn't contain code
* The common definitions should be split up into smaller, closely related components. The curent mix of definitions is not manageable

**Comment by RubenBG7** [comment]
complete replacement due to format problem in github view. Content modified are detailed in #149

**Comment by shilpa-padgaonkar** [comment]
@RubenBG7 This file is difficult to review as you have deleted the complete old content and added new. Could you please do  in place updates so that reviewers can exactly look at the changed parts? I would request you to close this PR and open a new one with in-plqce updates. 
Also, could you please create an issue first before creating a PR?

**Comment by shilpa-padgaonkar** [comment]
Based on confrimation from @RubenBG7, marking this as obsolete and closing the PR

**Pull request closed without merging**
