### PR TITLE
Click to Dial API proposal

### PR DESCRIPTION
**Pull request by HanbaiWang**
Hi all,
I filled out the proposal template of Click to Dial API, and China mobile want to create this API family project.
Please check whether there is any mistake in the filling of this template and whether there is anything that needs to be modified. Thank you!

### CODE REVIEW

**Comment by eric-murray** [comment]
@HanbaiWang
As this is an existing API / service, can you provide more details on the technical implementation. In particular, which network elements are involved (for a mobile network, in particular), and is the solution standardised or does it include some proprietary elements?

**Comment by HanbaiWang** [comment]
@eric-murray
Thanks for your question. Voice network support for outbound calls to calling and called party are needed for the support of this API. So some network element in the IMS are involved, such as AS and CSCF(TS 23.228 R18). For the  technical implementation of this API, the brief flow chart below may provide some help.
The solution is not standardised, but slightly related to the solution in TS 23.228(5.16.2.2.2) Release 18. The flow chart below also shows the need of couple of proprietary elements, such as Network Exposure Platform,AS(Audio and video capability network elements).  If you have any question for some more specific details, please feel free to ask at anytime.
3faf650b54af5b2c6f25c63eef43378

**Comment by eric-murray** [comment]
Thanks @HanbaiWang 
So would this API only be applicable for mobile networks, and only when both devices support VoLTE / VoNR?

**Comment by HanbaiWang** [comment]
@eric-murray
In our existing commercial cases, this API can be applied to both fixed and mobile numbers, including 2/3/4G and fixed users.

**Comment by HanbaiWang** [comment]
@eric-murray
Interworking with CS Domain can be done through MGCF network elements, which related to 3GPP TS 23.228.
For example, when I pull up a caller who clicks to dial, I can follow the flow of Network Exposure Platform -> AS -> CSCF -> BGCF -> MGCF -> GMSC -> UE to pull up a call to a CS domain user.

**Comment by HanbaiWang** [comment]
@jordonezlucena @eric-murray 
Sorry to bother，I would like to thank the members of the API Backlog Working Group for their initial evaluation of China Mobile's Click to Dial API application. I see that you have some questions about this API, mainly that the implementation is complex and not sure about the value on standardizing it. Could you please elaborate on these points and we can provide relevant explanatory materials to reflect the value of our API? Like the reasons of you think the implementation is complex. We can then provide relevant explanatory materials to reflect the value of our API!

**Comment by HanbaiWang** [comment]
Dear API Backlog Working Group members, In response to the last discussion, we've combed through some further information/details on Click-to-Dial API, including references to existing standard documents.This is presented in the following chunks.

**Comment by HanbaiWang** [comment]
1f9092f8297a9b39013ac1b9c627ee9

**Comment by HanbaiWang** [comment]
4486ae5439522d75cea0c94de7305a9
e7f17e7871c63ee3a146cdd1438414f
2cb54bb5155225655fd3859307476e9
0fb7ae3df304d056e37656c01a8d78f

**Comment by HanbaiWang** [comment]
[CTD 0824.pptx](https://github.com/camaraproject/WorkingGroups/files/12426483/CTD.0824.pptx)

**Comment by HanbaiWang** [comment]
[CTD 0824.pptx](https://github.com/camaraproject/WorkingGroups/files/12427990/CTD.0824.pptx)

**Review by jordonezlucena — APPROVED** [review]
The API proposal complies with the template.

**Pull request merged**
