### PR TITLE
Proposed Github issue and pull request templates

### LINKED ISSUE #163: Create issue and pr templates
Issue templates are helpful when we want to provide guidance for opening issues while allowing contributors to specify the content of their issues. 
Similarly PR templates help to describe and categorise the pull request better. It also helps creating better release documentation for sub-projects.

With this issue, we intend to create PR which will decide on a common issue and pr template that can be used across sub-projects. The intention is to follow best practises specified in the github documentation as well as use the issue and pr templates provided by project like K8s as reference for eg. https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by rartych**
This PR proposes set of templates to be used by Subprojects.
With draft templates the short How-to file describing configuration and usage of templates is added to the Commonalities documentation folder.

Fixes #163 .

### CODE REVIEW

**Comment by shilpa-padgaonkar** [comment]
@rartych : Would it make sense to extend the issue categories with "test"?
rest LGTM

**Review by bigludo7 — APPROVED** [review]
Seems to be a very good approach. 
As this internal to our 'CAMARA' team I think we should give a try to this proposal and update later if needed.

**Review by shilpa-padgaonkar — APPROVED** [review]
LGTM

**Review by RubenBG7 — APPROVED** [review]
Ok from TEF side

**Review by hdamker — APPROVED** [review]
LGTM - let's give it a try!

**Review by eric-murray — APPROVED** [review]

**Pull request merged**
