### PR TITLE
API Propsal for Consent and Measurement 

### PR DESCRIPTION
**Pull request by nickvenezia**
<!DOCTYPE` html><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; caret-color: rgb(31, 35, 40); color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"></p>
Field | Description
-- | --
API family name | "Consent & Measurement"
API family owner | Centillion.AI
API summary | The “Consent & Measurement” API suite is designed to provide the inputs necessary to power the world's digital ecosystem and protect Children. "Consent" is used to focus on a third-party usage of data. "CONSENT" CAN can be used by companies for fueling insights for audience planning, measuring ad exposure, along post campaign validation and audience contextual and behavioral lift measurement, Usage of data through auditing of AI and LLM usage, children's data usage  by third-parties with permissions set by the parents. The "Measurement" APIs are designed to integrate with leading enterprises needing consent for AI, Customer Data Platforms' (CDP), Data Management Platforms (DMP), Demand Side Platforms (DSP), Consent Management Platforms (CMP), ad tech companies both on the Sell Side (SSPs, DOOH, CTV, Publishers etc.) and the Buy Side (DSPs, Agency Trading Desks) and position the Mobile Network Operators (MNOs) as the digital backbone with MNO's holding the "consent" and the customers are ad-tech and AI for data aggregated with consent.  'Measurement' has a focus on helping identify real traffic,  and provides clarity for all parties. Leveraging the geospatial capabilities of the "CAMARA device location", natively integrated with a specific advertiser focused goals allow for an advertising experience focused on contextual targeting that provides privacy and adapts to local regulation, the goal is for minimizing ad-fraud, blocking access to those without consent, and these APIs provide a  new solution for the cookie day allowing for new innovative inputs that will streamline the $674B ad industry and trillion dollar forecasted AI Economy. The CAMARA provides "Measurement" capabilities that are a natural enhancement to advertisers and provide measurement lift in physical retail media and along with digital out of home device exposure (Rideshares, billboards, Points of interest). Leveraging conversion signals from "CarrierBillingCheckOut" (Purchase/digital transaction/click to call) enables both physical and digital transaction impact measurement, tying mobile device to ad exposure to audience behavior to business objectives. CAMARA's commitment to interoperability and compliance with industry standards is why we will be bringing both the IAB Tech Lab, Tradedesk, Bidswitch, and Prebid to aide with our dedication to providing interoperability based on a standardized ecosystem leveraging a dynamic consent verification framework.
Technical viability | The "Consent & Measurement" API family provides validated technical integrations with next generation ad tech and AI infrastructure, mass adoption potential with emerging industry standards, such as the Interactive Advertising Bureau (IAB) Tech Lab's. For MNOs and developers, this offers a path to long term viability, new revenue, and compliance across jurisdictions. By leveraging the scale of a standardized federated deployment, MNOs can reclaim revenue back from the tech industry that has created immense value on the back of the telecom infrastructure. By leveraging the structural advantages of the mobile network operators and provide a viable (if not superior alternative) to walled gardens (META / Google) "self-measurement" approach. CAMARA will uplift brands with greater transparency on ad measurement, the Consent and Measurement API will incentivize the adoption of the developer ecosystem with more ad revenue fueling innovation.
Commercial viability | The "Consent & Measurement" API has been proposed to leading conglomerate consumer brands, tech platforms, sell side publishers, buy side ad exchanges, and advertising trade organizations to gauge viability and industry adoption. When considering the commercial viability of the "Consent & Measurement" API, interested industry leaders gave it a unanimous “Yes.” The interested parties include LinkedIn, Univision, Proctor and Gamble, IAB Tech Lab, and TradeDesk.
YAML code available? | NO.
Validated in lab/productive environments? | NO.
Validated with real customers? | YES.   YES, the features of CAMARA API like Device Location can replace existing third-party tools used by brands which have been proven to be inaccurate.
Validated with operators? | NO. 
Supporters in API Backlog Working Group | Will be added by the Working Group.

### CODE REVIEW

**Comment by nickvenezia** [comment]
@MarkusKuemmerle PR submitted :)

**Comment by nickvenezia** [comment]
<!DOCTYPE` html><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; caret-color: rgb(31, 35, 40); color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"></p>
Field | Description
-- | --
API family name | "Consent & Measurement"
API family owner | Centillion.AI
API summary | The “Consent & Measurement” API suite is designed to provide the inputs necessary to power the world's digital ecosystem and protect Children. "Consent" is used to focus on a third-party usage of data. "CONSENT" CAN can be used by companies for fueling insights for audience planning, measuring ad exposure, along post campaign validation and audience contextual and behavioral lift measurement, Usage of data through auditing of AI and LLM usage, children's data usage  by third-parties with permissions set by the parents. The "Measurement" APIs are designed to integrate with leading enterprises needing consent for AI, Customer Data Platforms' (CDP), Data Management Platforms (DMP), Demand Side Platforms (DSP), Consent Management Platforms (CMP), ad tech companies both on the Sell Side (SSPs, DOOH, CTV, Publishers etc.) and the Buy Side (DSPs, Agency Trading Desks) and position the Mobile Network Operators (MNOs) as the digital backbone with MNO's holding the "consent" and the customers are ad-tech and AI for data aggregated with consent.  'Measurement' has a focus on helping identify real traffic,  and provides clarity for all parties. Leveraging the geospatial capabilities of the "CAMARA device location", natively integrated with a specific advertiser focused goals allow for an advertising experience focused on contextual targeting that provides privacy and adapts to local regulation, the goal is for minimizing ad-fraud, blocking access to those without consent, and these APIs provide a  new solution for the cookie day allowing for new innovative inputs that will streamline the $674B ad industry and trillion dollar forecasted AI Economy. The CAMARA provides "Measurement" capabilities that are a natural enhancement to advertisers and provide measurement lift in physical retail media and along with digital out of home device exposure (Rideshares, billboards, Points of interest). Leveraging conversion signals from "CarrierBillingCheckOut" (Purchase/digital transaction/click to call) enables both physical and digital transaction impact measurement, tying mobile device to ad exposure to audience behavior to business objectives. CAMARA's commitment to interoperability and compliance with industry standards is why we will be bringing both the IAB Tech Lab, Tradedesk, Bidswitch, and Prebid to aide with our dedication to providing interoperability based on a standardized ecosystem leveraging a dynamic consent verification framework.
Technical viability | The "Consent & Measurement" API family provides validated technical integrations with next generation ad tech and AI infrastructure, mass adoption potential with emerging industry standards, such as the Interactive Advertising Bureau (IAB) Tech Lab's. For MNOs and developers, this offers a path to long term viability, new revenue, and compliance across jurisdictions. By leveraging the scale of a standardized federated deployment, MNOs can reclaim revenue back from the tech industry that has created immense value on the back of the telecom infrastructure. By leveraging the structural advantages of the mobile network operators and provide a viable (if not superior alternative) to walled gardens (META / Google) "self-measurement" approach. CAMARA will uplift brands with greater transparency on ad measurement, the Consent and Measurement API will incentivize the adoption of the developer ecosystem with more ad revenue fueling innovation.
Commercial viability | The "Consent & Measurement" API has been proposed to leading conglomerate consumer brands, tech platforms, sell side publishers, buy side ad exchanges, and advertising trade organizations to gauge viability and industry adoption. When considering the commercial viability of the "Consent & Measurement" API, interested industry leaders gave it a unanimous “Yes.” The interested parties include LinkedIn, Univision, Proctor and Gamble, IAB Tech Lab, and TradeDesk.
YAML code available? | NO.
Validated in lab/productive environments? | YES . Mark and Toyeeb at Open Gateway.
Validated with real customers? | YES.   YES, the features of CAMARA API like Device Location can replace existing third-party tools used by brands which have been proven to be inaccurate.
Validated with operators? | NO. 
Supporters in API Backlog Working Group | Will be added by the Working Group.

**Comment by nickvenezia** [comment]
@jordonezlucena did I do this correctly?

**Comment by ShutingQing** [comment]
Hi Nick, thanks for your proposal. The desciption of the API value is pretty clear. Meanwhile, I'll suggest to clarify more clear on the API input and output, or like which exactly the ability is, how API caller can utilize the API under which exact scenario. That would be helpful.

**Comment by nickvenezia** [comment]
For Digital Out-of-Home (DOOH) ad exposure verification within a cross-platform measurement framework, an Application Programming Interface (API) can provide comprehensive analytics and insights, ensuring that advertisements reach their intended audience effectively across various channels.

### API Input for Cross-Platform DOOH Campaigns:

**Overview:**
The API is engineered to support DOOH campaigns integrated within broader omnichannel strategies. It collects vital information such as:

- **campaignId:** A unique identifier for the overarching campaign that spans multiple channels.
- **channelType:** Denotes the specific medium, such as Digital Out-of-Home, Online, or Social Media.
- **adId:** Unique identifier for the ad being showcased.
- **locationInfo:** Specific details related to the DOOH placement, like geographic location and screen dimensions.
- **timestamp:** The exact moment the ad was displayed to the audience.

**Example Input JSON:**
```json
{
  "campaignId": "campaign_67890",
  "channelType": "Digital Out-of-Home",
  "adId": "ad_12345",
  "locationInfo": {
    "latitude": "40.7128",
    "longitude": "-74.0060",
    "screenSize": "10x20 feet"
  },
  "timestamp": "2024-05-20T12:00:00Z"
}
```

### API Output for Cross-Platform DOOH Campaigns:

**Details Provided:**
The API delivers insights into ad performance across environments, including:

- **channelType:** Identifies the channel for which the response is relevant.
- **displayed:** Boolean indicating if the ad was shown as intended in the DOOH context.
- **interactionMetrics:** Engagement data such as viewer count and interaction duration, specific to the DOOH environment.
- **crossPlatformReach:** Measurement of how the DOOH ad's exposure complements other channels within the same campaign.

**Example Output JSON:**
```json
{
  "channelType": "Digital Out-of-Home",
  "displayed": true,
  "interactionMetrics": {
    "viewerCount": 300,
    "averageViewTime": "15 seconds"
  },
  "crossPlatformReach": {
    "onlineImpressions": 5000,
    "socialMediaEngagement": "high"
  }
}
```

### Application Scenario:

Imagine a marketing brand orchestrating a multifaceted advertising campaign for a high-profile product launch. The campaign employs an array of channels including DOOH, online banners, and social media platforms. By applying this API, the firm can evaluate the effectiveness of the DOOH components in conjunction with other digital efforts, allowing for a holistic view of the campaign’s reach and engagement. This enables the firm to adjust strategies in real-time, optimizing ad placements and timings based on data-driven insights, and ensuring a cohesive marketing message that resonates across all mediums.
This approach is particularly effective for campaigns aiming for maximum visibility and interaction, such as those leading up to major events or product launches, where synchronizing messages across platforms can significantly enhance overall campaign performance.

I will have more details in the presentation deck.

On Feb 29, 2024, at 9:24 PM, Miranda Tsing ***@***.***> wrote:

﻿

Hi Nick, thanks for your proposal. The desciption of the API value is pretty clear. Meanwhile, I'll suggest to clarify more clear on the API input and output, or like which exactly the ability is, how API caller can utilize the API under which exact scenario. That would be helpful.

**Comment by nickvenezia** [comment]
image

**Comment by nickvenezia** [comment]
@ShutingQing let me know if the image I shared helps at all.

**Comment by TEF-RicardoSerr** [comment]
Hello Nick, 
I suggest you to **_fill the template_** with a couple of user stories and also define the scope in the template (eg. This API aims to cover the following use cases...).

Also Nick, I need you to attend the [Backlog meetings](https://github.com/camaraproject/WorkingGroups/tree/main/APIBacklog#meetings) for the API discussions before the aproval by the TSC

**Comment by nickvenezia** [comment]
@TEF-RicardoSerr  where can I find the link to the calendar invite for the API Backlog. 

Have you looked at what I previously uploaded to the API Backlog folder for the presentations?

**Comment by nickvenezia** [comment]
@ShutingQing, What else could we add to this list? 

1. SCEF
2. SIP protocol
3. SMPTE Relative Timestamp
4. UPF
5.  NEF

These would all be relevant to help reduce ad fraud.

**Comment by ShutingQing** [comment]
Hi @nickvenezia , thanks for your response. :) Humbly give you some advices, hopefully can help your proposal getting appoved. 

As @TEF-RicardoSerr suggested, you can elaborate more on the API functions, scopes. Currently, in the table, API summary and techinical viability, **we can't know how developers call the api, how the api helps developers under which scenario.** This is the main problem. 
> I suggest you to fill the template with a couple of user stories and also define the scope in the template (eg. This API aims to cover the following use cases...).

Kindly find you some references, https://github.com/camaraproject/WorkingGroups/pulls?q=is%3Apr+is%3Aclosed .  My humble suggestions for the proposals is:
1) What's the API function?
For example, API functions is like, 1) QoD is helping developers adjusting QoS, from device to the Server(of the APP). Instant QoS Asjustment. End users may enjoy QoS accerlation by calling QoD post/put API.  2) SIM SWAP API is checking the matching changes between mobile phone number (MSISDN) and SIM card (IMSI). --> What about this API?
2) Scenario.
Ad fraud scenario, what Ad fraud scenario specifically?
For example, for SIM SWAP, since it is checking the matching history of MSISDN and IMSI. So by calling the API, API caller like banks, may know whether a customer who applied for a loan, is risky or not. Because, if a sim card is newly applied, then by calling SIM SWAP, banks can know. Then banks know here is a risky behavior. So SIM SWAP can helps on anti fraud scenario.

**Pull request closed without merging**
