### PR TITLE
Update APIBacklog.md

### PR DESCRIPTION
**Pull request by eric-murray**
Add Vodafone as supporter of Network Insights

### CODE REVIEW

**Comment by hdamker** [comment]
The API proposal was created under the name "Connectivity Insights". That need to be still reflected in the table.

**Comment by eric-murray** [comment]
Add Vodafone as supporter of Connectivity Insights!

**Comment by eric-murray** [comment]
@jordonezlucena
Can you approve and merge this PR? Thanks.

**Comment by jordonezlucena** [comment]
Replaced by #360

**Pull request closed without merging**
