### PR TITLE
Update APIBacklog.md

### PR DESCRIPTION
**Pull request by jordonezlucena**
Adding API proposal to live backlog table, with DT as supporter.

### CODE REVIEW

**Comment by MarkusKuemmerle** [comment]
[API_Lifecycle+feedback.xlsx](https://github.com/camaraproject/WorkingGroups/files/10472366/API_Lifecycle%2Bfeedback.xlsx)
Would you change the table according this XLS? (Use exact columns and column names because these are referenced in the process description)

**Review by MarkusKuemmerle — CHANGES_REQUESTED** [review]
See my last comment

**Comment by jordonezlucena** [comment]
@MarkusKuemmerle: updated

**Comment by MarkusKuemmerle** [comment]
I'm happy to change the table syntax from MD to HTML so that we're able to track changes easier.
But I would keep the information in the table as currently stated in the process description.
I've asked more CAMARA participants for a review of the process description so that we get more feedback from the community.

**Comment by hdamker** [comment]
I consider this PR as a draft, not ready for review until the process description is approved (I still hope that it will be **significantly** simplified). @MarkusKuemmerle: ok to set on draft?

**Comment by jordonezlucena** [comment]
> I consider this PR as a draft, not ready for review until the process description is approved (I still hope that it will be **significantly** simplified). @MarkusKuemmerle: ok to set on draft?

How dependent is this PR with the one under discussion in Governance (https://github.com/camaraproject/Governance/pull/65)? I think we can decouple them somehow -- the comments received in Governance are not yet related to the actual table and columns captured therein. I'd rather progress on this PR (regardless of the progress in https://github.com/camaraproject/Governance/pull/65, which seem to be still far from getting closed), with focus on 1) whether it makes sense to simplify this table, and ii) concrete solutions for this simplification.

**Comment by jordonezlucena** [comment]
Hi, I'd like to resume this activity, as newscomers and industry fora having a look at CAMARA repository claim the information captured in API backlog is quite deprecated -- they're totally right. 
Could we approve the latest version committed in MD file, and later think how we can turn the MD into HTML format? 
As I commented before, I think we can decouple this PR from #65

**Review by MarkusKuemmerle — APPROVED** [review]

**Review by hdamker — APPROVED** [review]

**Pull request merged**
