### PR TITLE
Update Glossary.md

### PR DESCRIPTION
**Pull request by shilpa-padgaonkar**
This change extends the glossary document so that it not only explains the meaning of the terms already used in the APIs/documentations but also suggests developer friendly alternatives for existing identifiers which if agreed within our Camara project, can be replaced from current APIs and documentation

Fixes https://github.com/camaraproject/WorkingGroups/issues/108

### CODE REVIEW

**Comment by shilpa-padgaonkar** [comment]
Issues have been created under every subproject to add their updates to the PR
https://github.com/camaraproject/QualityOnDemand/issues/90
https://github.com/camaraproject/HomeDevicesQoD/issues/20
https://github.com/camaraproject/EdgeCloud/issues/54
https://github.com/camaraproject/DeviceLocation/issues/12
https://github.com/camaraproject/OTPvalidationAPI/issues/11
https://github.com/camaraproject/NumberVerification/issues/10
https://github.com/camaraproject/DeviceStatus/issues/15
https://github.com/camaraproject/SimSwap/issues/11
https://github.com/camaraproject/CarrierBillingCheckOut/issues/45
https://github.com/camaraproject/AnonymisedSubscriberIdentifier/issues/4
https://github.com/camaraproject/DeviceIdentifier/issues/4

**Comment by shilpa-padgaonkar** [comment]
@FabrizioMoggio : The Intention is to not create too many documents that we would have to refer to in the end. Hence, a consolidated Glossary. I have changed the format of the doc slightly, which I hope would address your concerns.

**Comment by FabrizioMoggio** [comment]
@shilpa-padgaonkar: thank you, the modified table addresses my comment. Just one more comment, in my understanding the last column is to propose a possible alternative for the Parameter/Field. So, maybe, it should be:

"Alternative developer-friendly Parameter/Filed"

**Comment by shilpa-padgaonkar** [comment]
@eric-murray Those are just sample entries as stated in the note at the end of the document. Issues have been created under every subproject to add the real/actual entries they need with a description that accurately reflects the usage of the specified identifier. Feel free to update the entries as deemed fit.

I agree with your point that we would need to put more thought into some of the tricky terms/fields.
But IMHO, it will be difficult to start with perfect terms and descriptions. They will be refined over the course of time as we start  adding to the Glossary and it will be a living document for the project which matures over time.

**Comment by jordonezlucena** [comment]
@shilpa-padgaonkar: thanks for creating this PR. I agree we need to populate (and enhance) the table over course, as we get inputs from the Sub-Project leaders. 
Two suggestions on the proposed table:
- Add a new column called "In-scope APIs", just after or before "Usage in API (Parameter/Field)" column. This new column aims to list the CAMARA APIs that make use of this term. 
- Re-name "description" column to "definition". When providing the term definition, encourage contributor to include reference to relevant standard/industry fora (e.g., GSMA, ITU, 3GPP, IETF) where this term was originally defined.

**Comment by shilpa-padgaonkar** [comment]
@jordonezlucena : I can update description to definition.
For your first point, I can add the column, but I do wonder if all APIs will update this glossary regularly and keep it up to date or will it go stale over time! Also, we will then be expected to mention all the documentations where a term has been used (thereby making the list too long)?

**Comment by jordonezlucena** [comment]
> @jordonezlucena : I can update description to definition.
> For your first point, I can add the column, but I do wonder if all APIs will update this glossary regularly and keep it up to date or will it go stale over time! Also, we will then be expected to mention all the documentations where a term has been used (thereby making the list too long)?

My point is that, e.g. for "UeId", note that the API family "x", "y" and "z" make use of them. I'd not expect too many APIs make use of the same parameter. Anyway, we can try it out, and if we realise that it's quite complicated to keep this information updated, we can simply remove this column.

**Comment by shilpa-padgaonkar** [comment]
@PedroDiez and @eric-murray : Could you kindly update your contributions to use camelCase? I will then consolidate the contributions from other subprojects here myself.

**Comment by PedroDiez** [comment]
done @shilpa-padgaonkar

**Review by rartych — APPROVED** [review]

**Pull request merged**
