### PR TITLE
doc(guidelines): fix #168 - Add section on Discriminator usage in API-design-guidelines.md

### LINKED ISSUE #168: Add objectType property to our model used in oneOf or anyOf
As mentionned in Openapi doc [here](https://spec.openapis.org/oas/v3.1.0#discriminator-object) usage of discriminator may simplify serialization/deserialization process.

If we added an objectType property to our object involved in oneOf or anyOf sections we could add a section like this:
```
...
Object1:
  type: object
  properties:
    objectType: string
    ...
  required:
    - objectType
    - ...

Object2:
  type: object
  properties:
    objectType: string
    ...
  required:
    - objectType
    - ...

CompositeObject:
    type: object
    oneOf:
        - $ref: Object1
        - $ref: Object2
    discriminator:
        propertyName: objectType
```
to help serialization/deserialization process.
What do you think about this proposal?

### PR DESCRIPTION
**Pull request by patrice-conil**
As proposed in issue #168. Waiting for comments.

### CODE REVIEW

**Review by jlurien — CHANGES_REQUESTED** [review]
Asking for the inclusion of a `discriminator` property in the base class is enough to solve the problem and ease implementions. We may discuss on the convenience of having a shared name for it or not.  The `propertyName` is required as part of the discriminator, so it has to be explicitly indicated in all cases, and each API may choose the most meaningful name.
Defining an abstract schema as base class for all polymorphic objects just to define the common parameter does not save too much, and it does not allow to add a proper description to the type.  Moreover, in some cases the base class may include properties, other than the discriminator, shared by all children. Every API should be able to choose the most appropriate and meaningful base class if necessary.

**Comment by patrice-conil** [comment]
> Asking for the inclusion of a `discriminator` property in the base class is enough to solve the problem and ease implementions. We may discuss on the convenience of having a shared name for it or not. The `propertyName` is required as part of the discriminator, so it has to be explicitly indicated in all cases, and each API may choose the most meaningful name. Defining an abstract schema as base class for all polymorphic objects just to define the common parameter does not save too much, and it does not allow to add a proper description to the type. Moreover, in some cases the base class may include properties, other than the discriminator, shared by all children. Every API should be able to choose the most appropriate and meaningful base class if necessary.

@jlurien, 
I agree with you, new commit incorporates your remarks.

**Review by rartych — COMMENTED** [review]
I suggest to add payload example - as it is in OpenAPi doc.
BTW, if we decide to use OAS 3.0.3 - Issue https://github.com/camaraproject/WorkingGroups/issues/184 
then the link to doc should be: https://spec.openapis.org/oas/v3.0.3#discriminator-object (the content is the same I guess)

**Comment by patrice-conil** [comment]
> I suggest to add payload example - as it is in OpenAPi doc. BTW, if we decide to use OAS 3.0.3 - Issue #184 then the link to doc should be: https://spec.openapis.org/oas/v3.0.3#discriminator-object (the content is the same I guess)

@rartych, 
Thanks for your remarks, 
Job done in new commit

**Review by RubenBG7 — APPROVED** [review]
Reviewed from TEF side

**Review by shilpa-padgaonkar — APPROVED** [review]
/lgtm

**Pull request merged**
