### PR TITLE
API proposal for Network Insights #294

### PR DESCRIPTION
**Pull request by maheshc01**
API proposal related to OpenGateway Drop #2 Network Insight/Network Quality
* fixes issues #294

### CODE REVIEW

**Comment by maheshc01** [comment]
#294

**Comment by jordonezlucena** [comment]
The API proposal complies with the template

**Comment by jordonezlucena** [comment]
The API proposal has been sent to TSC approval

**Review by jordonezlucena — APPROVED** [review]
LGTM

**Pull request merged**
